### ISSUE TITLE
Source Link stop working

### ISSUE THREAD

**Issue by kdcllc** [kdcllc/Bet.AspNetCore#103]
According to the following discussions:

- https://github.com/dotnet/sdk/issues/1458#issuecomment-577292209
- https://github.com/dotnet/sdk/issues/1458#issuecomment-576961024
- https://github.com/dotnet/sourcelink/issues/244

The following must be updated in `settings.props` file:

```xml
<PropertyGroup>
  <DebugSymbols>True</DebugSymbols>
  <DebugType>Embedded</DebugType>
  <EmbedAllSources>True</EmbedAllSources>
</PropertyGroup>
```

**Comment by MikeBeaton** [comment]
You don't need `DebugSymbols` here, since it is overridden by `DebugType`.

You might want to be aware that those settings are not recommended for public packages, because it noticeably increases the size of the .nupkg and therefore download and restore times, by including debugging info and source files that only a few people will want or use. The better alternative for public repos is to use a separate .snupkg file (it which case you could use either SourceLink, which will work there, or no SourceLink and `EmbedAllSources` instead). For private or small audience size, repos the settings you've mentioned are fine and much easier to set up and use.

**Comment by kdcllc** [comment]
@MikeBeaton thanks for the explanation of these changes. The documentation is definitely is lacking. I am looking into redoing the deployment process altogether with publishing to NuGet symbol server.

- https://docs.microsoft.com/en-us/nuget/create-packages/symbol-packages-snupkg
- https://devblogs.microsoft.com/nuget/improved-package-debugging-experience-with-the-nuget-org-symbol-server/

```xml
<DebugType>portable</DebugType>

```bash
dotnet pack  Bet.AspNetCore.sln -p:configuration=Release -p:Version=2.1.0 -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg -o Packages -p:DebugType=portable

nuget push *.snupkg -Source https://api.nuget.org/v3/index.json
```
```
